export interface Plantao {
  id?: number,
  type?: string,
  local?: string,
  dstart?: string,
  hstart?: string,
  evalute?: number,
  comment?: string,
  other?: string,
  duration?: number | null,
  value?: number | null,
  company?: string,
  note?: boolean,
  payment?: boolean,
}
